# Generated by Django 4.1 on 2023-11-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
